name: Build Linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-linux-gfortran:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install Fortran compiler (gfortran)
      run: sudo apt-get install gfortran

    - name: Build package
      run: make