name: Build Linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-linux-gfortran:
    runs-on: ubuntu-latest

    env:
      CC: gcc
      FC: gfortran
      CXX: g++

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install Fortran compiler (gfortran)
      run: |
        sudo apt-get update
        sudo apt-get install -y gfortran gcc g++

    - name: Debug make
      run: make debug

    - name: Build base libraries
      run: make base

    - name: "Debug: List libs and headers"
      run: |
        echo -e "\n==============="
        echo "Built libraries"
        echo "==============="
        ls -lR build/lib
        echo -e "\n============="
        echo "Built headers"
        echo "============="
        ls -lR build/include

    - name: Build all libraries
      run: make all

    - name: Build package
      run: |
        make package PACK_VER=$(git describe --tags)
    
    - name: Upload package
      run: |
        curl -s -T $(ls *.tar.gz) \
          -u ${{ secrets.LIB_UPLOAD_USER}}:${{ secrets.LIB_UPLOAD_URL }} \
          testfile ${{ secrets.LIB_UPLOAD_URL }}